# Deploy static HTML/CSS/JavaScript To-Do app to Azure App Service

name: Deploy To-Do App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_19A02957FFE244B996700BA12511E5BF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F8AC6861393645ABA08E4E8F3B99CE5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C5C4F6A9FDBD4DD1A6CB1D22FE728799 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bovi-todo'
          slot-name: 'Production'
          package: '.'
